name: Build & Test
on:
  push:
    branches: ['**']  # Runs on any branch push (except tags)
    tags-ignore: ['*'] # Explicitly ignore tags
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle locally
        id: cache-gradle-local
        uses: maxnowack/local-cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - run: ./gradlew build --no-daemon